apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-metrics
  namespace: monitoring
  labels:
    k8s-app: prometheus
    prometheus: k8s
    role: service-monitor
spec:
  namespaceSelector:
    matchNames:
      - default
      - demo
  selector:
    matchLabels:
      app: backend
  endpoints:
  - targetPort: web
    interval: 30s
