apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - bases/manifests
  # - https://github.com/prometheus-operator/kube-prometheus.git?ref=release-0.7
configMapGenerator:
  - name: grafana-dashboard-argocd
    namespace: monitoring
    files:
      - dashboards/argocd.json
resources:
  - resources/app-serviceMonitor.yaml
patchesStrategicMerge:
  - patches/prometheus-clusterRole.yaml  
