apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: release-0.7
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
