apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/Modulus/argocd-demo.git #https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: HEAD #release-0.7
    path: prometheus

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring      