apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: metrics-demo
  namespace: demo
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: metrics-demo
  template:
    metadata:
      labels:
        app: metrics-demo
    spec:
      containers:
      - name: demo
        image: ghcr.io/modulus/argocd-demo-app:1.0.0
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 8000
        env: 
          - name: RUST_LOG
            value: info
  strategy:
    canary:
      analysis:
        templates:
          - templateName: success-rate
            startingStep: 3 # delay starting analysis run until setWeight: 40%
            args:
            - name: service-name
              value: metrics-demo.demo.svc.cluster.local        
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}        
