---
apiVersion: v1
kind: Service
metadata:
  name: metrics-demo
  namespace: demo
  labels:
    app: metrics-demo
spec:
  selector:
    app: metrics-demo
  ports:
  - port: 8000
    name: web
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: demo
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        env: 
          - name: HOST
            value: "http://metrics-demo:8000"
        image: ghcr.io/modulus/argocd-demo-app-locust:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"